### ISSUE TITLE
localised authentication

### ISSUE THREAD

**Issue by titanium-cranium** [hesto2/owlet-client#1]
Hi:
Been trying to work through implementing this for my own owlet but get stymied by the authentication immediately.  Perhaps because I'm located in Australia. How is locale being controlled?  

Cheers,

Brendan

Update:  I logged out of the app on my phone and logged in again using North America as the region and I've managed to get logged in and successfully retrieve data.  Unclear as yet what the region code is being used for other than maybe tech support?

**Comment by hesto2** [comment]
Interesting, glad you were able to find a workaround! Let me know if the client doesn't behave as expected and I'll take a look into adding support for localised auth.
